//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUI_QLSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string MaSinhVien { get; set; }
        public string MaMonHoc { get; set; }
        public Nullable<double> Diem1 { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
